CREATE DATABASE de_main;

CREATE TABLE de_main.translation
(
    id                 int primary key auto_increment,
    messageKey         varchar(255)  not null,
    messageTranslation varchar(2500) not null,
    localeId           varchar(5)    not null
);

CREATE TABLE de_main.inquiry
(
    id                     varchar(100) primary key,
    companyName            varchar(255) not null,
    companyLegal           varchar(100) not null,
    contactDialCode        varchar(10)  not null,
    contactDialCodeCountry varchar(10)  not null,
    contactTitle           varchar(100) not null,
    contactFirstname       varchar(100) not null,
    contactLastname        varchar(100) not null,
    contactEmail           varchar(100) not null,
    contactPhone           int          not null,
    addressStreet          varchar(255) not null,
    addressHouseNumber     int          not null,
    addressCity            varchar(100) not null,
    addressZip             int          not null,
    createdDate            date         not null
);

CREATE TABLE de_main.machine
(
    id                       varchar(100) primary key,
    serialNumberNotSpecified boolean      not null,
    serialNumber             varchar(100),
    type                     varchar(100) not null,
    machineWithAttachment    boolean      not null,
    modelsOfAttachments      varchar(1000),
    make                     varchar(100) not null,
    model                    varchar(100) not null,
    indemnity                varchar(100) not null,
    manufactureYear          int(4)       not null,
    usedOrNew                varchar(255) not null,
    taxDeductible            boolean      not null,
    price                    int          not null,
    leasingNumber            varchar(100) not null,
    insuranceStartDate       datetime     not null
);

CREATE TABLE de_main.inquiry_machine_link
(
    id        int primary key auto_increment,
    inquiryId varchar(100) not null,
    machineId varchar(100) not null,
    foreign key (inquiryId) references inquiry (id),
    foreign key (machineId) references machine (id)
);

INSERT INTO de_main.translation(messagekey, messagetranslation, localeid)
VALUES ('faq.header.1', 'Warum sollte ich eine Maschinenbruchversicherung statt einer Kaskoversicherung abschließen?', 'de-DE'),
       ('faq.body.1',
        'Die Kaskoversicherung ist eine Art Versicherung, die Schäden an Ihren landwirtschaftlichen Maschinen abdeckt, die durch verschiedene Ereignisse verursacht werden können, wie zum Beispiel Unfälle, Diebstahl oder Vandalismus. Diese Versicherung kann Schäden an Ihren Maschinen, einschließlich Traktoren, Erntemaschinen und anderen landwirtschaftlichen Geräten, abdecken. Die Maschinenbruchversicherung hingegen deckt Schäden an Ihren landwirtschaftlichen Maschinen ab, die durch interne Ursachen wie technische Defekte oder Bedienungsfehler verursacht werden. Diese Versicherung kann Reparaturkosten oder den Ersatz von beschädigten Teilen abdecken. Ein Beispiel für einen inneren Betriebsschaden, bei dem die Maschinenbruchversicherung greift, ist ein Motorschaden aufgrund eines technischen Defekts. Wenn beispielsweise der Motor aufgrund eines internen Fehlers ausfällt und dadurch die Maschine nicht mehr einsatzfähig ist, kann die Maschinenbruchversicherung die Kosten für die Reparatur des Motors abdecken.',
        'de-DE'),
       ('faq.header.2', 'Wann startet mein Versicherungsschutz?', 'de-DE'),
       ('faq.body.2', 'Der Versicherungsschutz startet gleichzeitig mit Finanzierungsbeginn bei der John Deere Bank S.A.', 'de-DE'),
       ('faq.header.3', 'Kann ich auch eine Versicherung ohne Finanzierung oder Leasing bei der John Deere Bank S.A. abschließen?', 'de-DE'),
       ('faq.body.3', 'Nein, der Versicherungsschutz ist nur möglich im Zusammenhang mit einer Finanzierung oder Leasing bei der John Deere Bank S.A.', 'de-DE'),
       ('faq.header.4', 'Wie lange dauert es, bis meine Versicherung aktiv ist?', 'de-DE'),
       ('faq.body.4', 'Der Versicherungsschutz startet gleichzeitig mit Finanzierungsbeginn bei der John Deere Bank S.A.. Sie bekommen eine automatische Bestätigung, wenn Ihr Versicherungsschutz startet. ', 'de-DE'),
       ('faq.header.5', 'Was passiert, wenn meine Finanzierung nicht genehmigt wird oder ich diese selber zurückziehe?', 'de-DE'),
       ('faq.body.5', 'Der Versicherungsschutz ist nur möglich im Zusammenhang mit einer Finanzierung oder Leasing bei der John Deere Bank S.A., d.h. die Finanzierung muss genehmigt werden. ', 'de-DE'),
       ('faq.header.6', 'Wen muss ich anrufen, wenn ich Fragen zum Versicherungsschutz habe?', 'de-DE'),
       ('faq.body.6', 'Bei allen Fragen rund um die Maschinenbruchversicherung können Sie sich jederzeit bei der folgenden Hotline melden: +49 (0) 69 867 906 281 oder unter der E-Mail Adresse maschinen.versicherung@marsh.com. ', 'de-DE'),
       ('faq.header.7', 'Wen muss ich kontaktieren, wenn ich einen Schadenfall habe?', 'de-DE'),
       ('faq.body.7',
        'Bitte senden Sie bei einem Schadenfall unverzüglich das ausgefüllte Schadenformular an claims.germany@marsh.com. Hier finden Sie das Schadenformular. Sie bekommen eine automatische Bestätigung, wenn der Schaden angelegt wurde. Man wird sich bei Ihnen melden, wenn weitere Informationen benötigt werden.',
        'de-DE'),
       ('faq.header.8', 'Haben Sie für die angefragte Maschine schon eine KFZ-Versicherung abgeschlossen? ', 'de-DE'),
       ('faq.body.8',
        'Zusätzlich zur Maschinenbruchversicherung bieten wir Ihnen auch eine Kfz-Haftpflicht für zulassungspflichtige Maschine an. Diese Versicherung übernimmt die Abwehr sowie Erstattung von Schadenersatzansprüchen, die von Dritten Ihnen gegenüber geltend gemacht werden.Für weitere Informationen zur Kfz-Haftpflicht wenden Sie sich bitte an uns. Sie können sich jederzeit bei uns unter der folgenden Hotline: +49 (0) 69 867 906 281 oder unter der E-Mail Adresse: maschinen.versicherung@marsh.com melden.',
        'de-DE'),
       ('card.header.1', 'Welche Maschinen können versichert werden?', 'de-DE'),
       ('card.body.1', 'Sowohl Neu- als auch Gebrauchtmaschinen können versichert werden. Dies gilt ausschließlich im Zusammenhang mit Leasing– oder Finanzierungsverträgen.', 'de-DE'),
       ('card.header.2', 'Habe ich Anspruch auf eine Ersatzmaschine?', 'de-DE'),
       ('card.body.2',
        'Ist ein versicherter Schaden eingetreten und Sie benötigen eine Ersatzmaschine, werden die Mietkosten ab dem dritten Tag übernommen. Dadurch ist sichergestellt, dass Sie sofort Ersatz haben, keine wichtige Zeit verlieren und weiter arbeiten können.',
        'de-DE'),
       ('card.header.3', 'Was wird bei einem Totalschaden ersetzt?', 'de-DE'),
       ('card.body.3', 'Bei Neugeräten innerhalb der ersten 24 Monate ab Erstinbetriebnahme wird der Neuwert entschädigt. Ab dem 25. Monat sowie bei Gebrauchtgeräten wird der Zeitwert erstattet.', 'de-DE'),
       ('card.header.4', 'Was wird bei einem Teilschaden ersetzt? ', 'de-DE'),
       ('card.body.4', 'Bei Schäden werden die Kosten im Rahmen der Versicherungsbedingungen für die Wiederherstellung des ursprünglichen Betriebszustandes der Maschine übernommen.', 'de-DE'),
       ('card.header.5', 'Maschinenbruchversicherung', 'de-DE'),
       ('card.body.5',
        'Die Maschinenbruchversicherung hingegen deckt Schäden an deinen landwirtschaftlichen Maschinen ab, die durch interne Ursachen wie technische Defekte oder Bedienungsfehler verursacht werden. Diese Versicherung kann Reparaturkosten oder den Ersatz von beschädigten Teilen abdecken.',
        'de-DE'),
       ('card.header.6', 'KFZ-Haftpflichtversicherung', 'de-DE'),
       ('card.body.6',
        'Auch für landwirtschaftliche Zugmaschinen schreibt der Gesetzgeber den Abschluss einer Kfz-Haftpflichtversicherung vor. Wir bieten Ihnen auch eine Kfz-Haftpflicht für zulassungspflichtige Maschinen an. Diese leistet bis zu einer Versicherungssumme von 100 Millionen Euro. Diese Versicherung übernimmt die Abwehr sowie Erstattung von Schadenersatzansprüchen, die von Dritten Ihnen gegenüber geltend gemacht werden.',
        'de-DE'),
       ('insured.point.1', 'Schäden durch Brand/Versengen', 'de-DE'),
       ('insured.point.2', 'Sachschäden durch Kurzschluss/Überspannung/Überstrom/Explosion', 'de-DE'),
       ('insured.point.3', 'Diebstahl/Einbruchdiebstahl/Raub', 'de-DE'),
       ('insured.point.4', 'Unfall beim Transport/Be- und Entladeschäden', 'de-DE'),
       ('insured.point.5', 'Interne Schäden an Betriebskomponenten (unvorhergesehener Schaden)', 'de-DE'),
       ('insured.point.6', 'Schäden durch Versagen der Mess-, Kontroll- oder Sicherheitstechnik ', 'de-DE'),
       ('insured.point.7', 'Sachschäden durch Wasser-, Öl- oder Schmiermittelmangel ', 'de-DE'),
       ('insured.point.8', 'Schäden während des Betriebs wie: Bedienungsfehler/ Ungeschicklichkeit/Unfall ', 'de-DE'),
       ('insured.point.9', 'Feuerlösch-, Bergungs- und Abschleppkosten sowie Eichkosten auf erstes Risiko bis insgesamt 200.000 Euro ', 'de-DE'),
       ('insured.point.10', 'Für Neumaschinen: Neuwertentschädigung in den ersten 24 Monaten ', 'de-DE'),
       ('insured.point.11', 'Sofortige Reparaturfreigabe bei Schäden bis 25.000 Euro ', 'de-DE'),
       ('insured.point.12', 'GAP-Deckung (Ausgleich der Lücke zwischen der Zeitwertentschädigung und dem noch abzulösenden Finanzierungsbetrag)', 'de-DE'),
       ('insured.point.13', 'Bereifung und Gummiketten sind zum Zeitwert mitversichert (Unfallschäden)', 'de-DE'),
       ('insured.point.14', 'Glasbruch 150 Euro bei Austausch', 'de-DE'),
       ('insured.point.15', 'Selbstbehalt 1.000 Euro oder 5.000 Euro für Neu- und Gebrauchtmaschinen', 'de-DE'),
       ('carousel.title', 'Ihre Maschine schon mit der Finanzierung absichern', 'de-DE'),
       ('carousel.button', 'Angebot berechnen', 'de-DE'),
       ('home.body.title', 'Maschinenbruchversicherung', 'de-DE'),
       ('home.body.1', 'Sie kennen die Gefahren, egal ob Sie nur eine Maschine oder einen ganzen Maschinenpark besitzen: Während der Lieferung, beim Ausladen und Aufbau oder beim Einsatz auf dem Feld – Schäden können jederzeit auftreten.', 'de-DE'),
       ('home.body.2',
        'Zusammen mit unseren Partnern - der Marsh GmbH als Versicherungsmakler und dem Risikoträger HDI Global SE - wurde ein Versicherungskonzept entwickelt, mit dem Sie Ihre Maschine gegen unvorhergesehene Schäden absichern können.', 'de-DE'),
       ('home.body.3', 'Hierzu unterhält die John Deere Insurance Agency GmbH einen Gruppenversicherungsvertrag mit HDI Global SE. Mitversichert ist John Deere Financial (John Deere Bank S.A.).', 'de-DE'),
       ('home.body.4', 'Sie können dieser Versicherung hier durch eine einfache Erklärung gegenüber der Marsh GmbH beitreten.', 'de-DE'),
       ('home.body.tos',
        '*Die Marsh GmbH ist der Versicherungsmakler nach § 34 d Abs. 1 GewO für die Maschinenbruchversicherung der John Deere Insurance Agency GmbH, zu der über diese Webseite der Beitritt erklärt werden kann. Weitere Informationen zur Marsh GmbH finden Sie ',
        'de-DE'),
       ('home.body.tos-here', 'hier.', 'de-DE'),
       ('footer.impressum', 'Impressum', 'de-DE'),
       ('footer.tos', 'Nutzungsbedingungen', 'de-DE'),
       ('footer.init-info', 'Erstinformationen', 'de-DE'),
       ('footer.privacy', 'Datenschutzerklärung', 'de-DE'),
       ('footer.cookies', 'Cookie-Richtlinie', 'de-DE'),
       ('footer.rights', 'Marsh GmbH. Alle Rechte vorbehalten.', 'de-DE'),
       ('menu.title', 'Menü', 'de-DE'),
       ('menu.faq', 'FAQ', 'de-DE'),
       ('menu.what-is-insured', 'Was ist versichert?', 'de-DE'),
       ('menu.contact', 'Kontaktieren Sie uns', 'de-DE'),
       ('inquiry.label.machineWithAttachment', 'Maschine mit Anbauten', 'de-DE'),
       ('inquiry.machine-number', 'Maschine hinzufügen', 'de-DE'),
       ('notification.error.header', 'Versicherungslösungen, die durch den Versicherungsmakler Marsh GmbH angeboten werden ', 'de-DE'),
       ('notification.success.header', 'Versicherungslösungen, die durch den Versicherungsmakler Marsh GmbH angeboten werden ', 'de-DE'),
       ('contactus.title', 'Kontaktieren Sie uns', 'de-DE'),
       ('contactus.name.label', 'Vor- und Nachname', 'de-DE'),
       ('contactus.name.placeholder', 'Max Mustermann', 'de-DE'),
       ('contactus.email.label', 'Email', 'de-DE'),
       ('contactus.email.placeholder', 'xxx@xxx.de', 'de-DE'),
       ('contactus.message.label', 'Nachricht', 'de-DE'),
       ('contactus.message.placeholder', 'Nachricht schreiben', 'de-DE'),
       ('contactus.button.send', 'Senden', 'de-DE'),
       ('inquiry.label.type', 'Maschinentyp', 'de-DE'),
       ('inquiry.placeholder.type', '- bitte wählen -', 'de-DE'),
       ('inquiry.label.make', 'Hersteller der Maschine', 'de-DE'),
       ('inquiry.placeholder.make', 'Bspw. John Deere', 'de-DE'),
       ('inquiry.label.model', 'Modell der Maschine', 'de-DE'),
       ('inquiry.placeholder.model', 'Bspw. Serie 6130 M oder 7R 330', 'de-DE'),
       ('inquiry.tooltip.model',
        'Bitte geben Sie das genaue Modell der Maschine an, wie es auch auf Ihrem Vertrag angegeben ist (bspw. 9RT 490) sowie auch die Anbauten, die zur Maschine gehören bspw. Vorrichtungen, Zusatzgeräte, Reserveteile und Fundamente.', 'de-DE'),
       ('inquiry.label.indemnity', 'Selbstbehalt in EUR', 'de-DE'),
       ('inquiry.placeholder.indemnity', 'Gewünschter Selbstbehalt', 'de-DE'),
       ('inquiry.tooltip.indemnity', 'Der Selbstbehalt ist der Betrag, den Sie im Schadensfall selbst tragen müssen.', 'de-DE'),
       ('inquiry.label.serialNumber', 'Seriennummer', 'de-DE'),
       ('inquiry.placeholder.serialNumber', '- bitte angeben -', 'de-DE'),
       ('inquiry.tooltip.serialNumber', 'Bitte geben Sie die Seriennummer Ihrer Maschine an, falls vorhanden.', 'de-DE'),
       ('inquiry.label.serialNumberNotSpecified', '', 'de-DE'),
       ('inquiry.label.manufactureYear', 'Baujahr der Maschine', 'de-DE'),
       ('inquiry.placeholder.manufactureYear', '- bitte wählen -', 'de-DE'),
       ('inquiry.label.taxDeductible', 'Vorsteuerabzugsberechtigung', 'de-DE'),
       ('inquiry.label.price2', 'Bruttoverkaufspreis in EUR', 'de-DE'),
       ('inquiry.label.price', 'Nettoverkaufspreis in EUR', 'de-DE'),
       ('inquiry.label.priceAttachment', 'plus Anbauten', 'de-DE'),
       ('inquiry.placeholder.price', 'Betrag in EUR', 'de-DE'),
       ('inquiry.tooltip.price', 'Bitte geben Sie den gesamten Netto - oder Bruttopreis der Maschine plus den Anbauten (bspw. Vorrichtungen, Zusatzgeräte, Reserveteile und Fundamente) an.', 'de-DE'),
       ('inquiry.label.leasingNumber', 'Finanzierungs-/Leasing-Projekt-Nr.', 'de-DE'),
       ('inquiry.placeholder.leasingNumber', '- bitte angeben -', 'de-DE'),
       ('inquiry.tooltip.leasingNumber', 'Bitte geben Sie die von der John Deere Bank S.A. erhaltene Finanzierungs-/Leasing-Projekt-Nr., auch sog. B-Nummer genannt, an. Diese finden Sie auf Ihrem Finanzierungs-oder Leasingvertrag.', 'de-DE'),
       ('inquiry.label.insuranceStartDate', 'Auslieferungsdatum / gewünschter Start des Versicherungsschutzes', 'de-DE'),
       ('inquiry.placeholder.insuranceStartDate', '- bitte wählen -', 'de-DE'),
       ('inquiry.tooltip.insuranceStartDate', 'Hier muss das derzeit mitgeteilte Auslieferungsdatum angegeben werden. Falls sich dieses ändert, wird die John Deere Bank S.A. dies mitteilen.', 'de-DE'),
       ('header.contact', 'Kontaktieren Sie uns', 'de-DE'),
       ('header.home', 'Versicherungslösungen, die durch den Versicherungsmakler Marsh GmbH angeboten werden*', 'de-DE'),
       ('button.back', 'Zurück', 'de-DE'),
       ('button.submit', 'Beitritt erklären', 'de-DE'),
       ('button.next', 'Weiter', 'de-DE'),
       ('inquiry.gap.tooltip', 'GAP Deckung', 'de-DE'),
       ('inquiry.finanzierung.tooltip', 'Gleichbleibende Prämie analog zur Finanzierung', 'de-DE'),
       ('inquiry.title.companyData', 'Unternehmensdaten', 'de-DE'),
       ('inquiry.label.companyName', 'Firmenname', 'de-DE'),
       ('inquiry.placeholder.companyName', 'Musterfirma ', 'de-DE'),
       ('inquiry.label.legal1', 'Rechtsform', 'de-DE'),
       ('inquiry.placeholder.legal1', 'bspw. GmbH', 'de-DE'),
       ('inquiry.title.contactPerson', 'Ansprechpartner ', 'de-DE'),
       ('inquiry.label.legal2', 'Anrede', 'de-DE'),
       ('inquiry.placeholder.legal2', 'Frau / Herr /Divers', 'de-DE'),
       ('inquiry.label.firstname', 'Vorname', 'de-DE'),
       ('inquiry.placeholder.firstname', 'Max', 'de-DE'),
       ('inquiry.label.lastname', 'Nachname', 'de-DE'),
       ('inquiry.placeholder.lastname', ' Mustermann', 'de-DE'),
       ('inquiry.label.email', 'E-Mail Adresse', 'de-DE'),
       ('inquiry.placeholder.email', 'max.mustermann@gmail.de', 'de-DE'),
       ('inquiry.label.phone', 'Telefonnummer', 'de-DE'),
       ('inquiry.placeholder.phone', '0173 XXX XXX', 'de-DE'),
       ('inquiry.title.address', 'Anschrift', 'de-DE'),
       ('inquiry.label.street', 'Straße', 'de-DE'),
       ('inquiry.placeholder.street', 'Musterstraße', 'de-DE'),
       ('inquiry.label.streetNumber', 'Hausnummer', 'de-DE'),
       ('inquiry.placeholder.streetNumber', '111', 'de-DE'),
       ('inquiry.label.city', 'Stadt', 'de-DE'),
       ('inquiry.placeholder.city', 'Musterstadt', 'de-DE'),
       ('inquiry.label.zipCode', 'Postleitzahl', 'de-DE'),
       ('inquiry.placeholder.zipCode', '11111', 'de-DE'),
       ('inquiry.title.postalAddress', 'Abweichende Postadresse', 'de-DE'),
       ('inquiry.label.differentPostal', 'Abweichende Postanschrift', 'de-DE'),
       ('inquiry.label.usedOrNew', 'Handelt es sich um eine neue oder gebrauchte Maschine?', 'de-DE'),
       ('inquiry.placeholder.usedOrNew', 'Neu / Gebraucht', 'de-DE'),
       ('inquiry.label.houseNumber', 'Hausnummer', 'de-DE'),
       ('inquiry.placeholder.houseNumber', '111', 'de-DE'),
       ('inquiry.label.step1', 'Risikoerfassung', 'de-DE'),
       ('inquiry.label.step2', 'Tarifübersicht', 'de-DE'),
       ('inquiry.label.step3', 'Kundeninformationen', 'de-DE'),
       ('inquiry.label.step4', 'Bestätigung', 'de-DE'),
       ('inquiry.description.step1', 'Angaben zur Maschine', 'de-DE'),
       ('inquiry.description.step2', 'Allgemeine Leistungen und Vertrag', 'de-DE'),
       ('inquiry.description.step3', 'Persönliche Daten', 'de-DE'),
       ('inquiry.description.step4', 'Beitrittserklärung', 'de-DE'),
       ('error.nonnegative', 'Der Wert muss eine positive Zahl sein', 'de-DE'),
       ('error.number', 'Dieses Feld muss eine Zahl sein', 'de-DE'),
       ('error.empty', 'Dieses Feld ist erforderlich', 'de-DE'),
       ('error.boolean', 'Dieses Feld muss angekreuzt werden', 'de-DE'),
       ('inquiry.no', 'Nein', 'de-DE'),
       ('inquiry.yes', 'Ja', 'de-DE'),
       ('inquiry.title.main', 'Maschinenversicherung', 'de-DE'),
       ('inquiry.label.serialNumberNotSpecified', 'Seriennummer nicht vorhanden', 'de-DE'),
       ('button.download', 'Dokument herunterladen', 'de-DE'),
       ('inquiry.machine.add', 'Maschine hinzufügen', 'de-DE'),
       ('contactus.validate.email-format', 'Bitte geben Sie eine gültige E-Mail-Adresse ein.', 'de-DE'),
       ('notification.success.header', 'Erfolg!', 'de-DE'),
       ('notification.success.body-contactus', 'Vielen Dank für Ihre Anfrage! Wir haben sie erhalten und werden uns bald bei Ihnen melden.', 'de-DE'),
       ('inquiry.label.modelsOfAttachments', 'Modell der Maschine und Anbauten', 'de-DE'),
       ('inquiry.placeholder.modelsOfAttachments', 'Bspw. John Deere T560 HM; John Deere 725X; Thalhammer Sww', 'de-DE'),
       ('inquiry.tooltip.modelsOfAttachments',
        'Bitte geben Sie das genaue Modell der Maschine und Anbauten an, wie es auch in Ihrem Vertrag angegeben ist (z. B. Maschine; Anbaugerät 1; Anbaugerät 2; etc.), und trennen Sie diese bitte mit einem Semikolon, wie im Beispiel.', 'de-DE'),
       ('inquiry.finish.header', 'Versicherungsschutz wurde erfolgreich beantragt', 'de-DE');

INSERT INTO de_main.translation(messagekey, messagetranslation, localeid)
VALUES ('notification.error.header', 'Insurance solutions offered by the insurance broker Marsh GmbH ', 'en-GB'),
       ('notification.success.header', 'Insurance solutions offered by the insurance broker Marsh GmbH ', 'en-GB'),
       ('contactus.title', 'Contact Us', 'en-GB'),
       ('contactus.name.label', 'Full Name', 'en-GB'),
       ('contactus.name.placeholder', 'Max Mustermann', 'en-GB'),
       ('contactus.email.label', 'Email', 'en-GB'),
       ('contactus.email.placeholder', 'xxx@xxx.de', 'en-GB'),
       ('contactus.message.label', 'Message', 'en-GB'),
       ('contactus.message.placeholder', 'Message', 'en-GB'),
       ('contactus.button.send', 'Send', 'en-GB'),
       ('inquiry.label.type', 'Machine type', 'en-GB'),
       ('inquiry.placeholder.type', '- Please choose -', 'en-GB'),
       ('inquiry.label.make', 'Manufacturer of the machine', 'en-GB'),
       ('inquiry.placeholder.make', 'e.g. John Deere', 'en-GB'),
       ('inquiry.label.model', 'Model of the machine', 'en-GB'),
       ('inquiry.placeholder.model', 'e.g. Series 6130 M or 7R 330', 'en-GB'),
       ('inquiry.tooltip.model', 'Please state the exact model of the machine as stated on your contract (e.g. 9RT 490) as well as the attachments belonging to the machine, e.g. devices, additional equipment, spare parts and foundations.', 'en-GB'),
       ('inquiry.label.indemnity', 'Deductible in EUR', 'en-GB'),
       ('inquiry.placeholder.indemnity', 'Desired Deductible', 'en-GB'),
       ('inquiry.tooltip.indemnity', 'The deductible is the amount you have to pay yourself in the event of a claim.', 'en-GB'),
       ('inquiry.label.serialNumber', 'Serial Number', 'en-GB'),
       ('inquiry.placeholder.serialNumber', '- please specify -', 'en-GB'),
       ('inquiry.tooltip.serialNumber', 'Please state the serial number of your machine, if available.', 'en-GB'),
       ('inquiry.label.serialNumberNotSpecified', 'Not specified', 'en-GB'),
       ('inquiry.label.manufactureYear', 'Year of manufacture', 'en-GB'),
       ('inquiry.placeholder.manufactureYear', '- Please choose -', 'en-GB'),
       ('inquiry.label.taxDeductible', 'Entitled to deduct input tax --> Yes or no, if yes Price in net, if no in gross', 'en-GB'),
       ('inquiry.label.pric2', 'Gross Price in EUR incl.', 'en-GB'),
       ('inquiry.label.price', 'Net Price in EUR incl.', 'en-GB'),
       ('inquiry.label.priceAttachment', 'plus attachments', 'en-GB'),
       ('inquiry.placeholder.price', 'Amount in EUR', 'en-GB'),
       ('inquiry.tooltip.price', 'Please state the total net or gross price of the machine plus the attachments (e.g. devices, additional equipment, spare parts and foundations).', 'en-GB'),
       ('inquiry.label.leasingNumber', 'Financing/Leasing-Project-Nr.', 'en-GB'),
       ('inquiry.placeholder.leasingNumber', '- please specify -', 'en-GB'),
       ('inquiry.tooltip.leasingNumber', 'Please state the financing/leasing project number, also known as the B number, that you received from John Deere Bank S.A.. You will find this on your financing or leasing contract.', 'en-GB'),
       ('inquiry.label.insuranceStartDate', 'Delivery date / desired start of insurance cover', 'en-GB'),
       ('inquiry.placeholder.insuranceStartDate', '- Please choose -', 'en-GB'),
       ('inquiry.tooltip.insuranceStartDate', 'The currently notified delivery date must be specified here. If this changes, John Deere Bank S.A. will inform you.', 'en-GB'),
       ('header.contact', 'Contact Us', 'en-GB'),
       ('header.home', 'Home', 'en-GB'),
       ('button.back', 'Back ', 'en-GB'),
       ('button.submit', 'Submit', 'en-GB'),
       ('button.next', 'Next ', 'en-GB'),
       ('inquiry.gap.tooltip', 'GAP coverage', 'en-GB'),
       ('inquiry.finanzierung.tooltip', 'Constant premium analogue to financing', 'en-GB'),
       ('inquiry.title.companyData', 'Company data', 'en-GB'),
       ('inquiry.label.companyName', 'Company name', 'en-GB'),
       ('inquiry.placeholder.companyName', 'Sample company', 'en-GB'),
       ('inquiry.label.legal1', 'Legal form', 'en-GB'),
       ('inquiry.placeholder.legal1', 'e.g. GmbH', 'en-GB'),
       ('inquiry.title.contactPerson', 'Contact person ', 'en-GB'),
       ('inquiry.label.legal2', 'Salutation', 'en-GB'),
       ('inquiry.placeholder.legal2', 'Mrs / Mr /Diverse', 'en-GB'),
       ('inquiry.label.firstname', 'First name', 'en-GB'),
       ('inquiry.placeholder.firstname', 'Max', 'en-GB'),
       ('inquiry.label.lastname', 'Surname', 'en-GB'),
       ('inquiry.placeholder.lastname', ' Mustermann', 'en-GB'),
       ('inquiry.label.email', 'E-mail address', 'en-GB'),
       ('inquiry.placeholder.email', 'max.mustermann@gmail.de', 'en-GB'),
       ('inquiry.label.phone', 'Telephone number', 'en-GB'),
       ('inquiry.placeholder.phone', '0173 XXX XXX', 'en-GB'),
       ('inquiry.title.address', 'Your address', 'en-GB'),
       ('inquiry.label.street', 'street', 'en-GB'),
       ('inquiry.placeholder.street', 'Sample street', 'en-GB'),
       ('inquiry.label.streetNumber', 'House number', 'en-GB'),
       ('inquiry.placeholder.streetNumber', '111', 'en-GB'),
       ('inquiry.label.city', 'City', 'en-GB'),
       ('inquiry.placeholder.city', 'Sample town', 'en-GB'),
       ('inquiry.label.zipCode', 'Postcode', 'en-GB'),
       ('inquiry.placeholder.zipCode', '11111', 'en-GB'),
       ('inquiry.title.postalAddress', 'Different postal address', 'en-GB'),
       ('inquiry.label.differentPostal', 'Different postal address', 'en-GB'),
       ('inquiry.label.usedOrNew', 'Is it a new or used machine?', 'en-GB'),
       ('inquiry.placeholder.usedOrNew', 'New / Used', 'en-GB'),
       ('inquiry.label.houseNumber', 'House number', 'en-GB'),
       ('inquiry.placeholder.houseNumber', '111', 'en-GB'),
       ('inquiry.label.step1', 'Risk identification', 'en-GB'),
       ('inquiry.label.step2', 'Rate overview', 'en-GB'),
       ('inquiry.label.step3', 'Customer information', 'en-GB'),
       ('inquiry.label.step4', 'Confirmation', 'en-GB'),
       ('inquiry.description.step1', 'Information on the machine', 'en-GB'),
       ('inquiry.description.step2', 'General services and contract', 'en-GB'),
       ('inquiry.description.step3', 'Personal data', 'en-GB'),
       ('inquiry.description.step4', 'Declaration of membership', 'en-GB'),
       ('error.nonnegative', 'The value has to be a positive number', 'en-GB'),
       ('error.number', 'This field has to be a number', 'en-GB'),
       ('error.empty', 'This field is required', 'en-GB'),
       ('error.boolean', 'This field has to be checked', 'en.GB'),
       ('inquiry.no', 'No', 'en-GB'),
       ('inquiry.yes', 'Yes', 'en-GB'),
       ('inquiry.title.main', 'Machinery insurance', 'en-GB');